In [3]:
import numpy as np
from numpy.random import randint as ri

In [22]:
mat1 = np.array(ri(1,10,9).reshape(3,3))
mat2 = np.array(ri(1,10,9).reshape(3,3))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", np.power(mat1,3),"\n----\n" ,np.power(mat2,3))
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.power(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[1 2 2]
 [7 3 7]
 [3 8 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 4 5]
 [4 4 7]
 [7 8 2]]

Addition
------------------
 [[ 6  6  7]
 [11  7 14]
 [10 16  3]]

Multiplication
------------------
 [[ 5  8 10]
 [28 12 49]
 [21 64  2]]

Division
------------------
 [[0.2        0.5        0.4       ]
 [1.75       0.75       1.        ]
 [0.42857143 1.         0.5       ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-7 -2 -4]
 [13  1  7]
 [-5  8 -1]]

Addition of a scalar (100)
-------------------------
 [[101 102 102]
 [107 103 107]
 [103 108 101]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  1   8   8]
 [343  27 343]
 [ 27 512   1]] 
----
 [[125  64 125]
 [ 64  64 343]
 [343 512   8]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[1.         1.41421356 1

In [67]:
from numpy.random import randint as ri
mat1 = np.array(ri(1,10,9).reshape(3,3))
mat2 = np.array(ri(1,10,9).reshape(3,3))
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",mat1.mean())


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = np.array(ri(1,99,9).reshape(3,3))
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 7 7]
 [8 4 3]
 [9 2 7]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 7 5]
 [6 7 1]
 [9 7 9]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 52

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [22 13 17]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [19 15 18]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [245  96 126]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [ 54 343  45]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.777777777777778

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2

In [25]:
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[1 2 2]
 [7 3 7]
 [3 8 1]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 4 5]
 [4 4 7]
 [7 8 2]]


In [68]:
#Q3
mat = np.array(ri(1,10,9).reshape(9,1))

In [69]:
mat

array([[1],
       [7],
       [2],
       [4],
       [8],
       [7],
       [9],
       [3],
       [2]])

In [ ]:
A = np.array(ri(1,100,10)) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",A.sort())


In [104]:
M = ri(1,100,25).reshape(5,5)  #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis = 1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis = 0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[72  6 51 46 46]
 [62  1 39  8 62]
 [43 48 82 26 22]
 [73 95 77 63 99]
 [84 83 85 73 23]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 6 46 46 51 72]
 [ 1  8 39 62 62]
 [22 26 43 48 82]
 [63 73 77 95 99]
 [23 73 83 84 85]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[43  1 39  8 22]
 [62  6 51 26 23]
 [72 48 77 46 46]
 [73 83 82 63 62]
 [84 95 85 73 99]]


In [127]:
# Fill the following ***** with appropriate solution.
a = np.array(ri(1,100,10))
b = np.array(ri(1,100,10))
c = np.array(ri(1,100,10))

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Max of a:", np.min(a))
print("Max of b:", np.min(b))


print("Max of a location:", np.argmin(a))
print("Max of b location:", np.argmin(b))
print("Max of c location:", np.argmin(c))



a: [37 68 99 71 59 48 77 92 30 41]
b: [16 36 45  4 92 20 41  1  8 70]
c: [91 39 80  1 50 51  9  2 51 17]
Max of a: 99
Max of b: 92
Max of a location: 2
Max of b location: 4
Max of c location: 0
Max of a: 30
Max of b: 1
Max of a location: 8
Max of b location: 7
Max of c location: 3


In [148]:
mat1 = np.array(ri(1,10,9).reshape(3,3))
mat2 = np.array(ri(1,10,9).reshape(3,3))

print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[4 4 2]
 [2 1 6]
 [4 9 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 8 7]
 [1 6 2]
 [5 4 3]]

Sq-root of 1st matrix using np
------------------
 [[2.         2.         1.41421356]
 [1.41421356 1.         2.44948974]
 [2.         3.         2.        ]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[5.45981500e+01 5.45981500e+01 7.38905610e+00]
 [7.38905610e+00 2.71828183e+00 4.03428793e+02]
 [5.45981500e+01 8.10308393e+03 5.45981500e+01]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.60205999 0.60205999 0.30103   ]
 [0.30103    0.         0.77815125]
 [0.60205999 0.95424251 0.60205999]]

Modulo reminder using np
 -------------------------------------------------- 
 [[1 4 2]
 [0 1 0]
 [4 1 1]]


In [168]:
print("Random number generation (from Uniform distribution)")
print(np.random.uniform(0,1,6).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.normal(0,1,9))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(low =1,high=10,size=5)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.multinomial(20, [1/6.]*6, size=1)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.00758422 0.25710774 0.44475936]
 [0.8430434  0.8078018  0.52223835]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[-1.08885532 -0.10185938 -1.26338582  1.62482967 -0.68820647 -0.837444
  0.1437959  -0.27789822 -1.14919543]
Random integer vector: [80 13 86 51  7 47 70 53 27 17]

Random integer matrix
[9 3 2 3 4]

20 samples drawn from a dice throw: [[3 1 3 1 9 3]]


In [192]:
#8.Find the nearest value from a given number in an array using NumPy.
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element
import numpy as np
x = np.random.uniform(1, 12, 5)
v = 4
n = x.flat[np.abs(x - v).argmin()]
print(n)


8.412209843951468
